### ISSUE TITLE
Getting reference from GetItems

### ISSUE THREAD

**Issue by Sinsei33** [llde/xOBSE#104]
I got a pretty simple script:

	Array_var invItems
	Array_var invTemp
	ref       rItem
	int       zzzTestVal1
	float     zzzTestVal2

	Begin GameMode

	let invTemp := ar_Construct Array
	let invItems := Player.GetItems 33

	ForEach invTemp<- invItems
    
		let rItem := invTemp["value"]

		if GetObjectCharge rItem != zzzTestVal1
			Set zzzTestVal1 to GetObjectCharge rItem
		EndIf

		if rItem.GetCurrentCharge > 0
			Set zzzTestVal2 to rItem.GetCurrentCharge 
		EndIf
	Loop

	Message TestVal1 %.0f. TestVal2 %0.f", zzzTestVal1, zzzTestVal2, 2

	let invTemp := ar_Null
	let invItems := ar_Null

	End

It is currently supposed to just give debug message. If i comment the GetCurrentCharge commands out there is no problem. But if the GetCurrentCharge commands are in the script the script simply will crash at those. I think it is some kind of problem with the reference? At least that's what i assume happens, because the GetObjectCharge requires a objectID:ref, while the GetCurrentCharge requires the reference for the call.

Is there any way how i can fix this?

At the end i want to update the charge of enchanted weapons via ModCurrentCharge or SetCurrentCharge, but both of those have the same kind of problem with the reference i think.

Thanks i advance!

**Comment by llde** [comment]
I would check if GetItems return properly the references correctly.

**Comment by Sinsei33** [comment]
How would i do that?

**Comment by llde** [comment]
The issue may be that GetItems doesn't seems to return a reference but a base object.
Honestly speaking the game should spit the error clearly in runtime at least. (Actually if you warp the GetCurrentCharge in an eval for the if and in a let for the second usage (instead if set) it should spit the issue clearly.)
You can use GetInvRefsForItem but in this case you may just try to use a container loop instead of cycling the container to get the item array, cycling the array to call GetInvRefsForItem and cycling the new array to operate on the ref itself. This has a too big complexity (both GetItems and GetInvRefsForItem traverse the container inventory completly, and the second to this for every element returned by GetItems so if unfiltered this is a O(n + n^2) scenario) while with container loops is an O(n) scenario so much simplier and faster.
