### ISSUE TITLE
Steamloader

### ISSUE THREAD

**Issue by snilex1** [llde/xOBSE#177]
Why is there a bootloader only for the Steam-version?
Why for the retail-version there is no such bootloader?
Well, to run the game with Oblivion Launcher I mean.

**Comment by snilex1** [comment]
Or for example if you play the GOG version

**Comment by llde** [comment]
the original game cannot understand the steam loader. The Steam loader is linked (or autoplugged during runtime) either by the steam client or by the steamworks library associated to Oblivion (the reason why this doesn't work with Proton).
If you want to use the launcher you have  2 options:
1)edit the Oblivion.exe to link to the obse DLL, or using a program, as MO2, that have the option to inject arbitrary dll 
2) Use a custom loader that is OBSE aware (either the mod of the vanilla one that just point to a bat instead of  the exe, or the more complex ones as OCOL)
