### ISSUE TITLE
v22.7 Causes Crash with Feature in Maskar's Oblivion Overhaul

### ISSUE THREAD

**Issue by AllisterHenderson** [llde/xOBSE#188]
CTD when feeding a tamed creature from MOO and using the imbuement tool from MOO. For more details please read this nexus [post](https://forums.nexusmods.com/index.php?showtopic=345909/#entry117926918).

**Comment by llde** [comment]
Seems like a change in 22.7 unearthed a serious bug.
the extradata internal pointer associating with the IR in the  loop isn't valid. (internal data pointer (first element of the linked list) is null)

**Comment by llde** [comment]
In the loops MOO call RemoveItemNS and AddItemNS, instead of operating directly on the IR. This potentially alter the informations in the container, and can cause the ExtraData in the IR to become invalid.
The AddItem doesn't seem much problematic as the loop is broken after the operations, but the Removal is
